const defaultState = () => {
  return {
    login: {
      token: localStorage.getItem('sessionToken') || null,
      isFetching: false,
      error: '',
    },
    userData: {
      user: {
        id: null,
        username: null,
        first_name: null,
        last_name: null,
      },
      accounts: [{
        deactivated: null,
        updated_at: null,
        margin_balances: {
          day_trade_buying_power: null,
          start_of_day_overnight_buying_power: null,
          overnight_buying_power_held_for_orders: null,
          cash_held_for_orders: null,
          created_at: null,
          day_trade_buying_power_held_for_orders: null,
          overnight_buying_power: null,
          marked_pattern_day_trader_date: null,
          cash: null,
          unallocated_margin_cash: null,
          updated_at: null,
          cash_available_for_withdrawal: null,
          margin_limit: null,
          outstanding_interest: null,
          uncleared_deposits: null,
          unsettled_funds: null,
          day_trade_ratio: null,
          overnight_ratio: null,
        },
        portfolio: null,
        cash_balances: null,
        withdrawal_halted: null,
        cash_available_for_withdrawal: null,
        type: null,
        sma: null,
        sweep_enabled: null,
        deposit_halted: null,
        buying_power: null,
        user: null,
        max_ach_early_access_amount: null,
        cash_held_for_orders: null,
        only_position_closing_trades: null,
        url: null,
        positions: null,
        created_at: null,
        cash: null,
        sma_held_for_orders: null,
        account_number: null,
        uncleared_deposits: null,
        unsettled_funds: null,
      }],
      selectedAccount: null,
      isFetching: false,
      error: '',
    },
    accountDetails: {
      portfolio: {
        excess_maintenance_with_uncleared_deposits: null,
        excess_maintenance: null,
        market_value: null,
        withdrawable_amount: null,
        last_core_market_value: null,
        unwithdrawable_deposits: null,
        extended_hours_equity: null,
        excess_margin: null,
        excess_margin_with_uncleared_deposits: null,
        equity: null,
        last_core_equity: null,
        adjusted_equity_previous_close: null,
        equity_previous_close: null,
        start_date: null,
        extended_hours_market_value: null,
      },
      positions: [{
        account: null,
        intraday_quantity: null,
        intraday_average_buy_price: null,
        url: null,
        created_at: null,
        updated_at: null,
        shares_held_for_buys: null,
        average_buy_price: null,
        instrument: null,
        shares_held_for_sells: null,
        quantity: null,
      }],
      quotes: [{
        ask_price: null,
        ask_size: null,
        bid_price: null,
        bid_size: null,
        last_trade_price: null,
        last_extended_hours_trade_price: null,
        previous_close: null,
        adjusted_previous_close: null,
        previous_close_date: null,
        symbol: null,
        trading_halted: null,
        last_trade_price_source: null,
        updated_at: null,
        instrument: null,
      }],
      isFetching: false,
      error: '',
    },
    instruments: [{
      min_tick_size: null,
      splits: null,
      margin_initial_ratio: null,
      url: null,
      quote: null,
      symbol: null,
      bloomberg_unique: null,
      list_date: null,
      fundamentals: null,
      state: null,
      country: null,
      day_trade_ratio: null,
      tradeable: null,
      maintenance_ratio: null,
      id: null,
      market: null,
      name: null,
    }],
  };
};

export default defaultState();
