const defaultState = () => {
  return {
    login: {
      token: localStorage.getItem('sessionToken') || null,
      isFetching: false,
      error: '',
    },
    userData: {
      user: {
        id: null,
        username: null,
        first_name: null,
        last_name: null,
      },
      accounts: [{
        account_number: null,
      }],
      selectedAccount: null,
      isFetching: false,
      error: '',
    },
    accountDetails: {
      account: {
        account_number: null,
        cash: null,
        cash_available_for_withdrawal: null,
        uncleared_deposits: null,
        unsettled_funds: null,
        buying_power: null,
      },
      portfolio: {
        excess_maintenance_with_uncleared_deposits: null,
        excess_maintenance: null,
        market_value: null,
        withdrawable_amount: null,
        last_core_market_value: null,
        unwithdrawable_deposits: null,
        extended_hours_equity: null,
        excess_margin: null,
        excess_margin_with_uncleared_deposits: null,
        equity: null,
        last_core_equity: null,
        adjusted_equity_previous_close: null,
        equity_previous_close: null,
        start_date: null,
        extended_hours_market_value: null,
      },
      positions: [{
        account: null,
        intraday_quantity: null,
        intraday_average_buy_price: null,
        url: null,
        created_at: null,
        updated_at: null,
        shares_held_for_buys: null,
        average_buy_price: null,
        instrument: null,
        shares_held_for_sells: null,
        quantity: null,
      }],
      quotes: [{
        "ask_price": null,
        "ask_size": null,
        "bid_price": null,
        "bid_size": null,
        "last_trade_price": null,
        "last_extended_hours_trade_price": null,
        "previous_close": null,
        "adjusted_previous_close": null,
        "previous_close_date": null,
        "symbol": null,
        "trading_halted": null,
        "last_trade_price_source": null,
        "updated_at": null,
        "instrument": null,
      }],
      instruments: [{
        min_tick_size: null,
        splits: null,
        margin_initial_ratio: 0.5000,
        url: null,
        quote: null,
        symbol: null,
        bloomberg_unique: null,
        list_date: null,
        fundamentals: null,
        state: null,
        country: null,
        day_trade_ratio: null,
        tradeable: null,
        maintenance_ratio: null,
        id: null,
        market: null,
        name: null,
      }],
      isFetching: false,
      error: '',
    },
  };
};

export default defaultState();
